# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

# Configured for using separate projects (more performant)
install! 'cocoapods',
generate_multiple_pod_projects: true,
incremental_installation: true
use_modular_headers!

target 'MarkdownView Example' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'MarkdownView', path: '../'
end
