included:
  - Sources

excluded:
  - Example
  - webassets

line_length:
  warning: 200
  error: 300

file_length:
  warning: 1200
  error: 2000

type_body_length:
  warning: 600
  error: 800

function_body_length:
  warning: 120
  error: 180

disabled_rules:
  - cyclomatic_complexity
  - force_cast
  - force_try
  - function_parameter_count
  - identifier_name
  - large_tuple
  - nesting
  - todo
  - trailing_whitespace
  - type_name
  - vertical_whitespace
  - weak_delegate
  - redundant_optional_initialization
  - redundant_string_enum_value
  - switch_case_alignment
